### ISSUE TITLE
Prestorybook dependency breaking the script [BUG]

### ISSUE THREAD

**Issue by sanyamdogra** [italia/design-react-kit#83]
**Describe the bug**
Prestorybook is breaking the 'npm run storybook' command in Next Branch.

**To Reproduce**
1. Checkout to Next branch from master.
2. Run 'npm run storybook'

**Expected behavior**
The command should work and open storybook at localhost.

**Screenshots**
![image](https://user-images.githubusercontent.com/33497630/53882507-81b74d80-403c-11e9-9fb9-26261797b1b3.png)

**Other Required Information (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
 Removing "prestorybook": "npm run install-dependencies", from package.json lets the script work fine. I'll post a PR once it is confirmed.

**Comment by francescozaia** [comment]
Tried to add [run-script-os](https://www.npmjs.com/package/run-script-os) but as I was expecting it isn't working on the very first install on Windows. 🤷‍♂️ 

https://github.com/italia/design-react-kit/blob/next/package.json#L70

**Comment by siddhant1** [comment]
Hey @sanyamdogra can you pull the source again and try , It was fixed with #77

**Comment by sanyamdogra** [comment]
Hey @siddhant1 this is for next branch and my branch is up to date. The error is still persisting and was not fixed by issue #77.

**Comment by sanyamdogra** [comment]
Works fine after migrating to `yarn`. Closing it.
